add_newline = true 
continuation_prompt = '▶▶ '

# Double the default timeouts
scan_timeout = 20
command_timeout = 1000

[directory]
truncation_symbol="…/"

[line_break]
disabled=true

[time]
disabled=false
